FROM ubuntu:24.10
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y
RUN apt-get update && apt install -y linux-libc-dev software-properties-common
RUN apt-get update && apt install -y \
nano \
htop \
openssh-server \
curl \
perl \
libnet-ssleay-perl \
openssl \
libauthen-pam-perl \
libpam-runtime \
libio-pty-perl \
unzip \
gcc \
gawk \
g++ \
build-essential \
libcap-dev \
libxml2-dev \
libssl-dev \
net-tools \
git \
python3-psycopg2 \
pandoc texlive-xetex \
texlive-fonts-recommended \
texlive-plain-generic \
ffmpeg \
p7zip \
golang


RUN apt-get update && apt install -y python3-pip python3.12-dev python3.12-venv
RUN python3.12 -m venv ~/_venv
RUN ~/_venv/bin/pip3 install --upgrade pip
COPY cfg/requirements_24.txt /root/requirements.txt
RUN ~/_venv/bin/pip3 install -r /root/requirements.txt

RUN ~/_venv/bin/jupyter notebook --generate-config && \
~/_venv/bin/jupyter nbextension install --py ipyparallel && \
~/_venv/bin/jupyter nbextension enable --py ipyparallel && \
~/_venv/bin/jupyter serverextension enable --py ipyparallel
RUN ls -lh ~/_venv/bin/

RUN ~/_venv/bin/ipython profile create
COPY cfg/jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py
COPY cfg/ipython_config.py /root/.ipython/profile_default/ipython_config.py
# empty password
COPY cfg/jupyter_notebook_config.json /root/.jupyter/jupyter_notebook_config.json



COPY bootstrap.sh /home/bootstrap.sh
EXPOSE 8000
EXPOSE 8001
ENTRYPOINT ["/bin/bash", "/home/bootstrap.sh"]



