version: '3.6'
services:
  jupyter:
    restart: always
    build:
      context: '.'
      dockerfile: "./Dockerfile"
    ports:
      - '8090:8000'
      - '8091:8001'
    volumes:
      - '${JUPYTER_HOME}:/home/data'
    shm_size: '4096m'