version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: mc
    ports:
      - 25565:25565
    environment:
      SERVER_NAME: "NewIsrael_21"
      MOTD: "Forge Minecraft Server"
      EULA: "TRUE"
      VERSION: "1.21.4"
      MODE: "survival"
      LEVEL_TYPE: "DEFAULT"
      ENABLE_RCON: "true"
      RCON_PASSWORD: password
      RCON_PORT: 28016
      SERVER_PORT: 25565
      MAX_PLAYERS: 20
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      PVP: "true"
      TZ: "Europe/Moscow"
      GUI: "FALSE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      ONLINE_MODE: "FALSE"
      # More aggressive settings for demo purposes
      AUTOPAUSE_TIMEOUT_INIT: "30"
      AUTOPAUSE_TIMEOUT_EST: "10"
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - ${MINECRAFT_DATA}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"