version: '3.6'
services:
  jenkinslocal:
    restart: always
    build:
      context: '.'
      dockerfile: "./Dockerfile"
    ports:
      - '${JENKINS_PORT}:8080'
      - '${JENKINS_AGENT_PORT}:50000'
    volumes:
      - '${JENKINS_HOME}:/var/jenkins_home'
      - '${JENKINS_SHARED}:/var/jenkins_share'
