version: '3.6'
services:
  ollama:
    restart: always
    container_name: ollama
    pull_policy: always
    tty: true
    build:
      context: '.'
      dockerfile: "./Dockerfile"
    ports:
      - '${O_PORT}:11434'
    volumes:
      - '${O_MODELS}:/root/.ollama'
    environment:
      - MODELS=llama3.3:latest,llama3.2:latest

