version: '3.8'
services:
  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${UBOOQUITY_DATA}:/config
      - ${UBOOQUITY_BOOKS}:/books
      - ${UBOOQUITY_COMICS}:/comics
      - ${UBOOQUITY_RAW}:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped