version: '3.6'
services:
  rtmp_nginx:
    restart: always
    build:
      context: '.'
      dockerfile: "./Dockerfile"
    ports:
      - '1935:1935'
      - '5050:5050'
    volumes:
      - '${RTMP_HOME}:/usr/share/nginx/html/hlslive'
    shm_size: '1024m'