version: '3.6'
services:
  mq:
    container_name: 'chest mq'
    build:
      context: '.'
      dockerfile: "./mq.Dockerfile"
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASS}'
      POSTGRES_HOST: '${PG_HOST}'
      POSTGRES_PORT: '${PG_PORT}'
      POSTGRES_DB: '${PG_DBNAME}'
    ports:
      - 15672:15672
    
